version: '3.8'

services:
  etf-trading-bot:
    build: .
    container_name: etf-trading-bot
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./logs:/app/logs
      - ./data:/app/data
      - ./.env:/app/.env
    networks:
      - etf-network
    depends_on:
      - postgres
    
  postgres:
    image: postgres:13
    container_name: etf-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: etf_trading
      POSTGRES_USER: etf_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - etf-network

  redis:
    image: redis:7-alpine
    container_name: etf-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - etf-network

networks:
  etf-network:
    driver: bridge

volumes:
  postgres_data:
